name: Protein-Sim
channels:
  - conda-forge
dependencies:
  - beautifulsoup4=4.12.2
  - conda=23.5.0
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.8.0
  - contourpy=1.0.7
  - faunus=2.9.1
  - ipykernel=6.22.0
  - ipython=8.12.0
  - jinja2=3.1.2
  - json5=0.9.5
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.5.0
  - jupyter_server_fileid=0.9.0
  - jupyter_server_terminals=0.4.4
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.3
  - jupyterlab_pygments=0.2.2
  - llvm-openmp=16.0.1
  - matplotlib=3.6.3
  - matplotlib-base=3.6.3
  - matplotlib-inline=0.1.6
  - mdtraj=1.9.7
  - nbclassic=0.5.5
  - nbclient=0.7.3
  - nbconvert=7.3.1
  - nbconvert-core=7.3.1
  - nbconvert-pandoc=7.3.1
  - nbformat=5.8.0
  - notebook-shim=0.2.2
  - numpy=1.24.2   
  - pandas=1.5.3
  - pip=23.0.1
  - python=3.10.14
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-json-logger=2.0.7
  - pyyaml=6.0  
  - readline=8.2
  - ruamel.yaml=0.17.31
  - ruamel.yaml.clib=0.2.7
  - ruamel_yaml=0.15.80
  - scipy=1.9.3
  - tqdm=4.65.0
  - yaml=0.2.5
  - pip:
      - ipywidgets==8.1.5
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-lsp==2.2.5
      - jupyterlab==4.3.5
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - mda-xdrlib==0.2.0
      - mdahole2==0.5.0
      - MDAnalysis==2.8.0      
      - nglview==3.1.4
      - notebook==7.3.2
